### ISSUE TITLE
Implementation in EMSCRIPTEN 

### ISSUE THREAD

**Issue by XU-YaoKun** [Maratyszcza/pthreadpool#16]
when compiling in EMSCRIPTEN environment, there is only `shim.c` got compiled.

This is the concerning CMakeLists.txt part, 

```
IF(EMSCRIPTEN)
  LIST(APPEND PTHREADPOOL_SRCS src/shim.c)
ELSE()
  LIST(APPEND PTHREADPOOL_SRCS src/portable-api.c src/memory.c)
  IF(APPLE AND (PTHREADPOOL_SYNC_PRIMITIVE STREQUAL "default" OR PTHREADPOOL_SYNC_PRIMITIVE STREQUAL "gcd"))
    LIST(APPEND PTHREADPOOL_SRCS src/gcd.c)
  ELSEIF(CMAKE_SYSTEM_NAME MATCHES "^(Windows|CYGWIN|MSYS)$" AND (PTHREADPOOL_SYNC_PRIMITIVE STREQUAL "default" OR PTHREADPOOL_SYNC_PRIMITIVE STREQUAL "event"))
    LIST(APPEND PTHREADPOOL_SRCS src/windows.c)
  ELSE()
    LIST(APPEND PTHREADPOOL_SRCS src/pthreads.c)
  ENDIF()
  IF(PTHREADPOOL_ENABLE_FASTPATH)
    LIST(APPEND PTHREADPOOL_SRCS src/fastpath.c)
  ENDIF()
ENDIF()
```

And after checking the implementation in that file, I found that all tasks are handled serially.

Here is a code snippet from `shim.c`,

```
void pthreadpool_parallelize_1d(
	struct pthreadpool* threadpool,
	pthreadpool_task_1d_t task,
	void* argument,
	size_t range,
	uint32_t flags)
{
	for (size_t i = 0; i < range; i++) {
		task(argument, i);
	}
}
```

As all tasks run in main thread, can I say that this thread pool does not support EMSCRIPTEN?

**Comment by Maratyszcza** [comment]
pthreadpool supports EMSCRIPTEN threads and even has optimizations for it, but only in Bazel build. CMake build always use single-thread fallback, mostly because [Emscripten CMake toolchain](https://github.com/emscripten-core/emscripten/blob/main/cmake/Modules/Platform/Emscripten.cmake) doesn't define any variable to distinguish builds with threading enabled/disabled. If you're looking to enable multithreading in pthreadpool, I suggest to start with the Emscripten CMake toolchain.
